"""Tests for ``promote_domain_to_repo`` — opt-in repo-wide glossary promotion.

The post-ship helper merges a feature's ``DOMAIN.md`` glossary into a
repo-wide ``.forge/domain/glossary.md``. Conflicts on duplicate terms with
diverging definitions are advisory and never block ship: the function
returns a ``PromotionResult`` with ``status="skipped"`` and the on-disk
glossary is left untouched. Term comparison is case-insensitive.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from tools.archive import (
    ArchiveError,
    ConflictRow,
    PromotionResult,
    promote_domain_to_repo,
)

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def _seed_feature_domain(repo_root: Path, feature_id: str, body: str) -> Path:
    feature_dir = repo_root / ".forge" / "features" / feature_id
    feature_dir.mkdir(parents=True)
    (feature_dir / "DOMAIN.md").write_text(body, encoding="utf-8")
    return feature_dir


def _seed_repo_glossary(repo_root: Path, body: str) -> Path:
    target = repo_root / ".forge" / "domain" / "glossary.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    return target


_FEATURE_DOMAIN_THREE_TERMS = """\
---
id: 2026-05-09-checkout
status: draft
---

# Domain Model

> Modeled subject summary.

# Glossary

| Term | Definition | Context | Invariants |
|---|---|---|---|
| Order | A confirmed customer purchase | sales | Total >= 0 |
| Cart | A pending list of items before checkout | sales | — |
| Customer | A person placing an order | — | — |
"""


# ---------------------------------------------------------------------------
# Happy-path cases
# ---------------------------------------------------------------------------


def test_promote_clean_no_existing_repo_glossary(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)

    result = promote_domain_to_repo(tmp_path, feature_id)

    assert isinstance(result, PromotionResult)
    assert result.status == "ok"
    assert sorted(result.promoted_terms) == ["Cart", "Customer", "Order"]
    assert result.skipped_terms == []
    assert result.conflicts == []

    glossary_path = tmp_path / ".forge" / "domain" / "glossary.md"
    assert glossary_path.is_file()
    text = glossary_path.read_text(encoding="utf-8")
    assert text.startswith("# Repo-Wide Domain Glossary")
    # Sorted alphabetically by term — Cart, Customer, Order.
    cart_pos = text.index("| Cart ")
    customer_pos = text.index("| Customer ")
    order_pos = text.index("| Order ")
    assert cart_pos < customer_pos < order_pos
    # Source feature column populated.
    assert feature_id in text


def test_promote_partial_overlap_skips_existing(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Cart | A pending list of items before checkout | 2026-04-01-cart-init |\n"
        "| Order | A confirmed customer purchase | 2026-04-01-cart-init |\n",
    )

    result = promote_domain_to_repo(tmp_path, feature_id)

    assert result.promoted_terms == ["Customer"]
    assert sorted(result.skipped_terms) == ["Cart", "Order"]
    assert result.conflicts == []


def test_promote_conflict_returns_skipped_status_without_writing(tmp_path: Path) -> None:
    """Per locked plan P1.7: conflict path never blocks ship — returns advisory."""
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    repo_glossary_body = (
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Order | A different definition entirely | 2026-04-01-some-feature |\n"
    )
    glossary_path = _seed_repo_glossary(tmp_path, repo_glossary_body)

    result = promote_domain_to_repo(tmp_path, feature_id)

    assert result.status == "skipped"
    assert result.promoted_terms == []
    assert result.skipped_terms == []
    assert len(result.conflicts) == 1
    conflict = result.conflicts[0]
    assert conflict.term == "Order"
    assert conflict.feature_definition == "A confirmed customer purchase"
    assert conflict.repo_definition == "A different definition entirely"
    # The on-disk glossary must be unchanged.
    assert glossary_path.read_text(encoding="utf-8") == repo_glossary_body


def test_promote_missing_domain_md_raises(tmp_path: Path) -> None:
    feature_id = "2026-05-09-no-domain"
    feature_dir = tmp_path / ".forge" / "features" / feature_id
    feature_dir.mkdir(parents=True)

    with pytest.raises(ArchiveError, match=r"DOMAIN\.md missing"):
        promote_domain_to_repo(tmp_path, feature_id)


def test_promote_rejects_traversal_feature_id(tmp_path: Path) -> None:
    """``feature_id`` must validate against ``_FEATURE_ID_RE`` before any path math."""
    # Set up a DOMAIN.md outside .forge/features that a traversal id could read.
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "DOMAIN.md").write_text(
        "# Glossary\n\n"
        "| Term | Definition | Context | Invariants |\n"
        "|---|---|---|---|\n"
        "| Pwn | should never be promoted | — | — |\n",
        encoding="utf-8",
    )
    # Create .forge/features so the traversal would otherwise succeed.
    (tmp_path / ".forge" / "features").mkdir(parents=True)

    with pytest.raises(ArchiveError, match="invalid feature id"):
        promote_domain_to_repo(tmp_path, "../../outside")

    # Repo-wide glossary must NOT have been written.
    assert not (tmp_path / ".forge" / "domain" / "glossary.md").exists()


def test_promote_case_insensitive_term_dedup(tmp_path: Path) -> None:
    """Repo ``order`` and feature ``Order`` must collide on case-insensitive key."""
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    glossary_path = _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| order | A confirmed customer purchase | 2026-04-01-prior |\n",
    )

    result = promote_domain_to_repo(tmp_path, feature_id)

    # Same term modulo case + same definition modulo case → skip, no duplicate row.
    assert result.status == "ok"
    assert "Order" in result.skipped_terms
    final = glossary_path.read_text(encoding="utf-8")
    # Display spelling preserved from the existing repo row.
    order_lines = [line for line in final.splitlines() if line.lower().startswith("| order")]
    assert len(order_lines) == 1, order_lines
    assert order_lines[0].startswith("| order ")


def test_promote_case_insensitive_term_conflict(tmp_path: Path) -> None:
    """Repo ``order`` and feature ``Order`` with diverging definitions surface a conflict."""
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    repo_body = (
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| order | A wholly different concept | 2026-04-01-prior |\n"
    )
    glossary_path = _seed_repo_glossary(tmp_path, repo_body)

    result = promote_domain_to_repo(tmp_path, feature_id)

    assert result.status == "skipped"
    assert any(c.term.lower() == "order" for c in result.conflicts)
    # Glossary file unchanged.
    assert glossary_path.read_text(encoding="utf-8") == repo_body


def test_promote_atomic_write_no_partial(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    original = (
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Cart | A pending list of items before checkout | 2026-04-01-cart-init |\n"
    )
    glossary_path = _seed_repo_glossary(tmp_path, original)

    with (
        patch("tools.archive.os.replace", side_effect=OSError("disk full")),
        pytest.raises(OSError, match="disk full"),
    ):
        promote_domain_to_repo(tmp_path, feature_id)

    # File untouched on disk.
    assert glossary_path.read_text(encoding="utf-8") == original


def test_promote_appends_source_feature_to_existing_row(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Cart | A pending list of items before checkout | 2026-04-01-cart-init |\n",
    )

    promote_domain_to_repo(tmp_path, feature_id)

    final = (tmp_path / ".forge" / "domain" / "glossary.md").read_text(encoding="utf-8")
    # The Cart row's source-features cell now lists both features.
    cart_line = next(line for line in final.splitlines() if line.startswith("| Cart "))
    assert "2026-04-01-cart-init" in cart_line
    assert feature_id in cart_line


def test_promote_idempotent_re_run(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)

    first = promote_domain_to_repo(tmp_path, feature_id)
    glossary_path = tmp_path / ".forge" / "domain" / "glossary.md"
    snapshot_after_first = glossary_path.read_text(encoding="utf-8")

    second = promote_domain_to_repo(tmp_path, feature_id)

    assert first.status == "ok"
    assert sorted(first.promoted_terms) == ["Cart", "Customer", "Order"]
    assert second.status == "ok"
    assert second.promoted_terms == []
    assert sorted(second.skipped_terms) == ["Cart", "Customer", "Order"]
    assert second.conflicts == []
    # File contents stable across re-runs.
    assert glossary_path.read_text(encoding="utf-8") == snapshot_after_first


def test_promote_reads_archived_domain_path(tmp_path: Path) -> None:
    """Caller can pass ``feature_dir`` pointing at the archived feature path."""
    feature_id = "2026-05-09-checkout"
    archived_dir = tmp_path / ".forge" / "features" / "archive" / feature_id
    archived_dir.mkdir(parents=True)
    (archived_dir / "DOMAIN.md").write_text(_FEATURE_DOMAIN_THREE_TERMS, encoding="utf-8")

    result = promote_domain_to_repo(tmp_path, feature_id, feature_dir=archived_dir)

    assert result.status == "ok"
    assert sorted(result.promoted_terms) == ["Cart", "Customer", "Order"]


def test_promote_definition_normalization(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    # Repo definition for Order has trailing whitespace + double internal spaces.
    _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain (post-ship advisory). Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Order | A confirmed   customer purchase   | 2026-04-01-cart-init |\n",
    )

    result = promote_domain_to_repo(tmp_path, feature_id)

    # Whitespace differences are normalized away — no conflict, Order skipped.
    assert "Order" in result.skipped_terms
    assert result.conflicts == []


def test_conflict_row_dataclass_shape() -> None:
    row = ConflictRow(
        term="Order",
        feature_definition="A confirmed customer purchase",
        repo_definition="A different definition entirely",
    )
    assert row.term == "Order"
    assert row.feature_definition == "A confirmed customer purchase"
    assert row.repo_definition == "A different definition entirely"
