"""Tests for ``promote_domain_to_repo`` — opt-in repo-wide glossary promotion.

The ship-time helper merges a feature's ``DOMAIN.md`` glossary into a
repo-wide ``.forge/domain/glossary.md``. Conflicts on duplicate terms with
diverging definitions block the promotion (atomic — no partial writes).
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

import tools.archive as archive_mod
from tools.archive import (
    ArchiveError,
    ConflictRow,
    PromotionResult,
    promote_domain_to_repo,
)

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def _seed_feature_domain(repo_root: Path, feature_id: str, body: str) -> Path:
    feature_dir = repo_root / ".forge" / "features" / feature_id
    feature_dir.mkdir(parents=True)
    (feature_dir / "DOMAIN.md").write_text(body, encoding="utf-8")
    return feature_dir


def _seed_repo_glossary(repo_root: Path, body: str) -> Path:
    target = repo_root / ".forge" / "domain" / "glossary.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    return target


_FEATURE_DOMAIN_THREE_TERMS = """\
---
id: 2026-05-09-checkout
status: draft
---

# Domain Model

> Modeled subject summary.

# Glossary

| Term | Definition | Context | Invariants |
|---|---|---|---|
| Order | A confirmed customer purchase | sales | Total >= 0 |
| Cart | A pending list of items before checkout | sales | — |
| Customer | A person placing an order | — | — |
"""


# ---------------------------------------------------------------------------
# Happy-path cases
# ---------------------------------------------------------------------------


def test_promote_clean_no_existing_repo_glossary(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)

    result = promote_domain_to_repo(tmp_path, feature_id)

    assert isinstance(result, PromotionResult)
    assert sorted(result.promoted_terms) == ["Cart", "Customer", "Order"]
    assert result.skipped_terms == []
    assert result.conflicts == []

    glossary_path = tmp_path / ".forge" / "domain" / "glossary.md"
    assert glossary_path.is_file()
    text = glossary_path.read_text(encoding="utf-8")
    assert text.startswith("# Repo-Wide Domain Glossary")
    # Sorted alphabetically by term — Cart, Customer, Order.
    cart_pos = text.index("| Cart ")
    customer_pos = text.index("| Customer ")
    order_pos = text.index("| Order ")
    assert cart_pos < customer_pos < order_pos
    # Source feature column populated.
    assert feature_id in text


def test_promote_partial_overlap_skips_existing(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain. Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Cart | A pending list of items before checkout | 2026-04-01-cart-init |\n"
        "| Order | A confirmed customer purchase | 2026-04-01-cart-init |\n",
    )

    result = promote_domain_to_repo(tmp_path, feature_id)

    assert result.promoted_terms == ["Customer"]
    assert sorted(result.skipped_terms) == ["Cart", "Order"]
    assert result.conflicts == []


def test_promote_conflict_blocks_with_archiveerror(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    repo_glossary_body = (
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain. Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Order | A different definition entirely | 2026-04-01-some-feature |\n"
    )
    glossary_path = _seed_repo_glossary(tmp_path, repo_glossary_body)

    with pytest.raises(ArchiveError, match="glossary conflicts"):
        promote_domain_to_repo(tmp_path, feature_id)

    # The on-disk glossary must be unchanged.
    assert glossary_path.read_text(encoding="utf-8") == repo_glossary_body


def test_promote_missing_domain_md_raises(tmp_path: Path) -> None:
    feature_id = "2026-05-09-no-domain"
    feature_dir = tmp_path / ".forge" / "features" / feature_id
    feature_dir.mkdir(parents=True)

    with pytest.raises(ArchiveError, match="DOMAIN.md missing"):
        promote_domain_to_repo(tmp_path, feature_id)


def test_promote_atomic_write_no_partial(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    original = (
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain. Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Cart | A pending list of items before checkout | 2026-04-01-cart-init |\n"
    )
    glossary_path = _seed_repo_glossary(tmp_path, original)

    with patch.object(archive_mod.os, "replace", side_effect=OSError("disk full")):
        with pytest.raises(OSError, match="disk full"):
            promote_domain_to_repo(tmp_path, feature_id)

    # File untouched on disk.
    assert glossary_path.read_text(encoding="utf-8") == original


def test_promote_appends_source_feature_to_existing_row(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain. Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Cart | A pending list of items before checkout | 2026-04-01-cart-init |\n",
    )

    promote_domain_to_repo(tmp_path, feature_id)

    final = (tmp_path / ".forge" / "domain" / "glossary.md").read_text(encoding="utf-8")
    # The Cart row's source-features cell now lists both features.
    cart_line = next(line for line in final.splitlines() if line.startswith("| Cart "))
    assert "2026-04-01-cart-init" in cart_line
    assert feature_id in cart_line


def test_promote_idempotent_re_run(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)

    first = promote_domain_to_repo(tmp_path, feature_id)
    glossary_path = tmp_path / ".forge" / "domain" / "glossary.md"
    snapshot_after_first = glossary_path.read_text(encoding="utf-8")

    second = promote_domain_to_repo(tmp_path, feature_id)

    assert sorted(first.promoted_terms) == ["Cart", "Customer", "Order"]
    assert second.promoted_terms == []
    assert sorted(second.skipped_terms) == ["Cart", "Customer", "Order"]
    assert second.conflicts == []
    # File contents stable across re-runs.
    assert glossary_path.read_text(encoding="utf-8") == snapshot_after_first


def test_promote_definition_normalization(tmp_path: Path) -> None:
    feature_id = "2026-05-09-checkout"
    _seed_feature_domain(tmp_path, feature_id, _FEATURE_DOMAIN_THREE_TERMS)
    # Repo definition for Order has trailing whitespace + double internal spaces.
    _seed_repo_glossary(
        tmp_path,
        "# Repo-Wide Domain Glossary\n\n"
        "> Auto-generated by /forge:ship --promote-domain. Do not edit by hand.\n\n"
        "| Term | Definition | Source feature(s) |\n"
        "|---|---|---|\n"
        "| Order | A confirmed   customer purchase   | 2026-04-01-cart-init |\n",
    )

    result = promote_domain_to_repo(tmp_path, feature_id)

    # Whitespace differences are normalized away — no conflict, Order skipped.
    assert "Order" in result.skipped_terms
    assert result.conflicts == []


def test_conflict_row_dataclass_shape() -> None:
    row = ConflictRow(
        term="Order",
        feature_definition="A confirmed customer purchase",
        repo_definition="A different definition entirely",
    )
    assert row.term == "Order"
    assert row.feature_definition == "A confirmed customer purchase"
    assert row.repo_definition == "A different definition entirely"
